version: "3.7"

services:
  database:
    image: mongo:4.4
    container_name: pi-iv-database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  splash:
    image: scrapinghub/splash
    container_name: scraping_splash
    ports:
      - 8050:8050

  scrappers:
    container_name: pi-iv-scrappers
    build:
      context: scrappers
    environment:
      DB_URL: mongodb://admin:admin@database:27017/
      DB_NAME: 'pi-iv'
    depends_on:
      - splash
      - database

  api:
    container_name: pi-iv-api
    ports:
    - 5001:5001
    build:
      context: api
    environment:
      DB_URL: mongodb://admin:admin@database:27017/
      DB_NAME: 'pi-iv'
    depends_on:
      - database

  web:
    container_name: pi-iv-web
    build:
      context: web
    ports:
      - 8080:8080
